#!/bin/sh

if [ "$ACTION" = "reset" -a "$BUTTON" = "wps" ]; then
	uptime
	xqled sys_off;xqled func_off
	echo "Reset key is reset" | tee /dev/console
	ap_mode=$(uci -q get xiaoqiang.common.NETMODE)
	if [ "$ap_mode" = "whc_cap" ]; then
		ubus call xq_info_sync_mqtt restore
	fi
fi
