#!/bin/sh /etc/rc.common

START=98
USE_PROCD=1
PROG=/usr/sbin/netapi

start_service() {
    #not work for ap-mode
    ap_mode=$(uci -q get xiaoqiang.common.NETMODE)
    [ "$ap_mode" = "lanapmode" -o "$ap_mode" = "wifiapmode" -o "$ap_mode" = "whc_re" ] && exit 0

    [ -f "$PROG" ] && {
	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn
	procd_close_instance
    }
}

