#!/bin/sh /etc/rc.common

START=99
start() {
    if [ ! -d "/userdisk/appdata/notuninstallable" ]; then
        cp -a /usr/share/datacenter/appdata/* /userdisk/appdata/
    fi
    mount --bind /userdisk/appdata /usr/share/datacenter/appdata
    /usr/share/datacenter/appdata/notuninstallable/plugin/server_check.sh&
    #/userdisk/appdata/plugin/server_check.sh&
    #/userdisk/appdata/plugin/port_count.sh&
    return 0
}

stop() {
    killall server_check.sh
    killall Plugin
    return 0
}


