#!/bin/sh /etc/rc.common

START=99
STOP=20
USE_PROCD=1
RESPAWN_THRESHOLD=120
RESPAWN_TIMEOUT=20
RESPAWN_RETRIES=40960000

export PROCLINE="/usr/sbin/wolink -l 7 -m 0"

check_ras_key() {
    key=`uci -q get china_unicom.unicom.rsae`
    if [ "x$key" = "x" ]; then
        curl http://localhost/cgi-bin/luci/api/system/update_rsa_key
    fi
}

start_service() {
    netmode=$(uci -q get xiaoqiang.common.NETMODE)
    if [ "$netmode" == "whc_re" ]; then
        echo "The NETMODE is whc_re, wolink must not start!!!"
        return 0
    fi

    inited=`uci -q get xiaoqiang.common.INITTED`
    if [ "x$inited" != "xYES" ]; then
        return 0
    fi
    check_ras_key
    procd_open_instance
    procd_set_param command ${PROCLINE}
    procd_set_param respawn ${RESPAWN_THRESHOLD} ${RESPAWN_TIMEOUT} ${RESPAWN_RETRIES}
    procd_close_instance
    return 0
}
