#!/bin/sh

netmode="`uci -q get xiaoqiang.common.NETMODE`"
if [ "${netmode}" != "whc_re" ]; then
        echo "not re, exit"
        exit 1
fi

wpa_supplicant_exist="`ps w | grep -w "wpa_supplicant -g" | grep -v grep | wc -l`"
[ ${wpa_supplicant_exist} -ne 1 ] && exit 1

ifname="`uci -q get misc.backhauls.backhaul_5g_sta_iface`"
driver="nl80211"
bridge="br-lan"

sleep 5
[ -f "/var/run/wpa_supplicant-$ifname.lock" ] && {
	wpa_cli -g /var/run/wpa_supplicantglobal interface_remove $ifname
	rm /var/run/wpa_supplicant-$ifname.lock
}
sed -i '/bssid=00:00:00:00:00:00/d' /var/run/wpa_supplicant-$ifname.conf
wpa_cli -g /var/run/wpa_supplicantglobal interface_add $ifname /var/run/wpa_supplicant-$ifname.conf $driver /var/run/wpa_supplicant-$ifname "" $bridge
touch /var/run/wpa_supplicant-$ifname.lock

backhaul_5g="`uci show misc.backhauls.backhaul_5g_sta_iface|awk -F "'" '{print $2}'`"
index="`uci show wireless|grep ifname|grep $backhaul_5g|awk -F "." '{print $2}'`"
bestbssid="`uci -q get wireless.$index.bssid`"
if [ -n "$bestbssid" -a "$bestbssid" != "00:00:00:00:00:00" ]; then
	wpa_cli -p /var/run/wpa_supplicant-$ifname -i $ifname set_network 0 bssid "$bestbssid"
fi

